"""EventGraph — hash-chained, append-only, causal event graph."""

from .authority import (
    AuthorityChain,
    AuthorityLink,
    AuthorityPolicy,
    AuthorityResult,
    DefaultAuthorityChain,
    matches_action,
)
from .actor import (
    Actor,
    ActorFilter,
    ActorStatus,
    ActorStore,
    ActorType,
    ActorUpdate,
    InMemoryActorStore,
)
from .bus import EventBus
from .decision import (
    AuthorityLevel,
    Branch,
    Condition,
    DecisionError,
    DecisionNode,
    DecisionOutcome,
    DecisionTree,
    EvaluateInput,
    EvolutionConfig,
    EvolutionResult,
    IDecisionMaker,
    IIntelligence,
    IntelligenceUnavailableError,
    InternalNode,
    LeafNode,
    LeafStats,
    MatchValue,
    NoOpIntelligence,
    Operator,
    PathStep,
    PatternResult,
    Response,
    TreeResult,
    TreeStats,
    detect_pattern,
    evaluate,
    evolve,
    extract_branch,
    extract_field,
    parse_outcome,
    test_condition,
)
from .errors import (
    ActorKeyNotFoundError,
    ActorNotFoundError,
    ChainIntegrityError,
    EmptyRequiredError,
    EventGraphError,
    EventNotFoundError,
    InvalidFormatError,
    InvalidTransitionError,
    OutOfRangeError,
    StoreError,
    ValidationError,
)
from .event import (
    Event,
    NoopSigner,
    Signer,
    canonical_content_json,
    canonical_form,
    compute_hash,
    create_bootstrap,
    create_event,
    new_event_id,
)
from .primitive import (
    LIFECYCLE_ACTIVE,
    LIFECYCLE_ACTIVATING,
    LIFECYCLE_DORMANT,
    LIFECYCLE_EMITTING,
    LIFECYCLE_MEMORIAL,
    LIFECYCLE_PROCESSING,
    LIFECYCLE_SUSPENDED,
    LIFECYCLE_SUSPENDING,
    AddEvent,
    Mutation,
    Primitive,
    PrimitiveState,
    Registry,
    Snapshot,
    UpdateActivation,
    UpdateLifecycle,
    UpdateState,
)
from .primitives import (
    ALL_PRIMITIVE_CLASSES,
    create_all_primitives,
)
from .grammar import Grammar
from .compositions import (
    AlignmentGrammar,
    ArbitrationResult,
    AuctionResult,
    BarterResult,
    BeingFarewellResult,
    BeingGrammar,
    BelongingGrammar,
    BetrayalRepairResult,
    BondFarewellResult,
    BondGrammar,
    BondMentorshipResult,
    BuildGrammar,
    CheckInResult,
    ClassActionResult,
    CommonsGovernanceResult,
    ConstitutionalAmendmentResult,
    ContemplationResult,
    CredentialResult,
    CulturalOnboardingResult,
    DelegateAndVerifyResult,
    DesignReviewResult,
    EscalateResult,
    EthicsAuditResult,
    EvolutionGrammar,
    ExileResult,
    ExistentialAuditResult,
    FactCheckResult,
    FederationResult,
    FestivalResult,
    ForecastResult,
    GuardrailResult,
    HealthCheckResult,
    IdentityAuditResult,
    IdentityGrammar,
    ImpactAssessmentResult,
    InjunctionResult,
    IntroductionResult,
    JusticeGrammar,
    KnowledgeBaseResult,
    KnowledgeGrammar,
    MarketGrammar,
    MarketSubscriptionResult,
    MeaningGrammar,
    MeaningMentorshipResult,
    MeaningPostMortemResult,
    MigrationResult,
    MilestoneResult,
    OnboardResult,
    PhaseTransitionResult,
    PipelineResult,
    PleaResult,
    PollResult,
    PostMortemResult,
    PruneResult,
    RecallResult,
    ReinventionResult,
    RenewalResult,
    ReputationTransferResult,
    RestorativeJusticeResult,
    RetirementResult,
    RetrospectiveResult,
    RefundResult,
    SchismResult,
    SelfEvolveResult,
    SocialGrammar,
    SpikeResult,
    SprintResult,
    StandupResult,
    SuccessionResult,
    SurveyResult,
    TechDebtResult,
    TransferResult,
    TriageResult,
    TrialResultJ,
    VerifyResult,
    WhistleblowResult,
    WorkGrammar,
)
from .graph import (
    AlreadyBootstrappedError,
    Graph,
    GraphClosedError,
    GraphConfig,
    GraphNotStartedError,
    Query,
)
from .intelligence import (
    ClaudeCliProvider,
    Config as IntelligenceConfig,
    ConfigError as IntelligenceConfigError,
    IntelligenceError,
    OpenAICompatibleProvider,
    Provider,
    ProviderError,
    new_claude_cli_config,
    new_provider,
)
from .sqlite_store import SQLiteStore
from .store import ChainVerification, InMemoryStore, Store
from .trust import DefaultTrustModel, TrustConfig, TrustMetrics
from .tick import TickConfig, TickEngine, TickResult
from .egip import (
    # Constants
    CURRENT_PROTOCOL_VERSION,
    MAX_ENVELOPE_AGE_SECONDS,
    DEDUP_PRUNE_INTERVAL,
    INTER_SYSTEM_DECAY_RATE,
    INTER_SYSTEM_MAX_ADJUSTMENT,
    TRUST_IMPACT_VALID_PROOF,
    TRUST_IMPACT_RECEIPT_ON_TIME,
    TRUST_IMPACT_TREATY_HONOURED,
    TRUST_IMPACT_TREATY_VIOLATED,
    TRUST_IMPACT_INVALID_PROOF,
    TRUST_IMPACT_SIGNATURE_INVALID,
    TRUST_IMPACT_NO_HELLO_RESPONSE,
    # Enums
    MessageType,
    TreatyStatus,
    TreatyAction,
    ReceiptStatus,
    ProofType,
    CGERRelationship,
    AuthorityLevel as EGIPAuthorityLevel,
    # Identity
    IIdentity,
    SystemIdentity,
    # Envelope
    Envelope as EGIPEnvelope,
    sign_envelope,
    verify_envelope,
    # Payloads
    CGER,
    HelloPayload,
    MessagePayloadContent,
    ReceiptPayload,
    ProofPayload,
    TreatyPayload,
    TreatyTerm,
    AuthorityRequestPayload as EGIPAuthorityRequestPayload,
    DiscoverPayload,
    DiscoverQuery,
    DiscoverResult,
    ChainSegmentProof,
    EventExistenceProof,
    ChainSummaryProof,
    # Version negotiation
    negotiate_version,
    # Treaty
    Treaty,
    new_treaty,
    # Stores & infra
    PeerRecord,
    PeerStore,
    TreatyStore,
    EnvelopeDedup,
    Handler as EGIPHandler,
    # Proof
    ProofGenerator,
    validate_proof,
    verify_chain_segment,
    verify_event_existence,
    # Transport
    ITransport,
    # Errors
    EGIPError,
    SystemNotFoundError as EGIPSystemNotFoundError,
    EnvelopeSignatureInvalidError,
    TreatyViolationError,
    TrustInsufficientError,
    TransportFailureError,
    DuplicateEnvelopeError,
    TreatyNotFoundError,
    VersionIncompatibleError,
)
from .codegraph import (
    # Primitive classes
    ALL_CODEGRAPH_PRIMITIVE_CLASSES,
    CGEntity,
    CGProperty,
    CGRelation,
    CGCollection,
    CGState as CGStatePrimitive,
    CGEvent as CGEventPrimitive,
    CGTransform,
    CGCondition,
    CGSequence,
    CGLoop,
    CGTrigger,
    CGConstraint,
    CGQuery as CGQueryPrimitive,
    CGCommand,
    CGSubscribe as CGSubscribePrimitive,
    CGAuthorize as CGAuthorizePrimitive,
    CGSearch as CGSearchPrimitive,
    CGInterop,
    CGDisplay,
    CGInput,
    CGLayout,
    CGList,
    CGForm,
    CGAction as CGActionPrimitive,
    CGNavigation,
    CGView,
    CGFeedback,
    CGAlert,
    CGThread,
    CGAvatar,
    CGAudit,
    CGDrag,
    CGSelection,
    CGConfirmation,
    CGEmpty,
    CGLoading,
    CGPagination,
    CGPalette,
    CGTypography,
    CGSpacing,
    CGElevation,
    CGMotion,
    CGDensity,
    CGShape,
    CGAnnounce,
    CGFocus,
    CGContrast,
    CGSimplify,
    CGRecency,
    CGHistory,
    CGLiveness,
    CGUndo,
    CGRetry,
    CGFallback,
    CGOffline,
    CGScope,
    CGFormat,
    CGGesture,
    CGPresence,
    CGSalience,
    CGConsequencePreview,
    # Compositions
    CodeGraphComposition,
    all_codegraph_compositions,
    all_codegraph_primitives,
    board as codegraph_board,
    dashboard as codegraph_dashboard,
    detail as codegraph_detail,
    feed as codegraph_feed,
    inbox as codegraph_inbox,
    is_codegraph_primitive,
    register_all_codegraph,
    skin as codegraph_skin,
    wizard as codegraph_wizard,
    # Event types
    all_codegraph_event_types,
    CODEGRAPH_ENTITY_DEFINED,
    CODEGRAPH_ENTITY_MODIFIED,
    CODEGRAPH_ENTITY_RELATED,
    CODEGRAPH_STATE_TRANSITIONED,
    CODEGRAPH_LOGIC_TRANSFORM_APPLIED,
    CODEGRAPH_LOGIC_CONDITION_EVALUATED,
    CODEGRAPH_LOGIC_SEQUENCE_EXECUTED,
    CODEGRAPH_LOGIC_LOOP_ITERATED,
    CODEGRAPH_LOGIC_TRIGGER_FIRED,
    CODEGRAPH_LOGIC_CONSTRAINT_VIOLATED,
    CODEGRAPH_IO_QUERY_EXECUTED,
    CODEGRAPH_IO_COMMAND_EXECUTED,
    CODEGRAPH_IO_COMMAND_REJECTED,
    CODEGRAPH_IO_SUBSCRIBE_REGISTERED,
    CODEGRAPH_IO_AUTHORIZE_GRANTED,
    CODEGRAPH_IO_AUTHORIZE_DENIED,
    CODEGRAPH_IO_SEARCH_EXECUTED,
    CODEGRAPH_IO_INTEROP_SENT,
    CODEGRAPH_IO_INTEROP_RECEIVED,
    CODEGRAPH_UI_VIEW_RENDERED,
    CODEGRAPH_UI_ACTION_INVOKED,
    CODEGRAPH_UI_NAVIGATION_TRIGGERED,
    CODEGRAPH_UI_FEEDBACK_EMITTED,
    CODEGRAPH_UI_ALERT_DISPATCHED,
    CODEGRAPH_UI_DRAG_COMPLETED,
    CODEGRAPH_UI_SELECTION_CHANGED,
    CODEGRAPH_UI_CONFIRMATION_RESOLVED,
    CODEGRAPH_AESTHETIC_SKIN_APPLIED,
    CODEGRAPH_TEMPORAL_UNDO_EXECUTED,
    CODEGRAPH_TEMPORAL_RETRY_ATTEMPTED,
    CODEGRAPH_RESILIENCE_OFFLINE_ENTERED,
    CODEGRAPH_RESILIENCE_OFFLINE_SYNCED,
    CODEGRAPH_STRUCTURAL_SCOPE_DEFINED,
    CODEGRAPH_SOCIAL_PRESENCE_UPDATED,
    CODEGRAPH_SOCIAL_SALIENCE_TRIGGERED,
)
from .agent import (
    # FSM
    OperationalState,
    # Primitive classes
    ALL_AGENT_PRIMITIVE_CLASSES,
    ActPrimitive as AgentActPrimitive,
    AttenuationPrimitive as AgentAttenuationPrimitive,
    AuthorityPrimitive as AgentAuthorityPrimitive,
    BudgetPrimitive as AgentBudgetPrimitive,
    ChannelPrimitive as AgentChannelPrimitive,
    CommunicatePrimitive as AgentCommunicatePrimitive,
    CompositionPrimitive as AgentCompositionPrimitive,
    ConsentPrimitive as AgentConsentPrimitive,
    DecidePrimitive as AgentDecidePrimitive,
    DelegatePrimitive as AgentDelegatePrimitive,
    EscalatePrimitive as AgentEscalatePrimitive,
    EvaluatePrimitive as AgentEvaluatePrimitive,
    ExpectPrimitive as AgentExpectPrimitive,
    GoalPrimitive as AgentGoalPrimitive,
    IdentityPrimitive as AgentIdentityPrimitive,
    IntrospectPrimitive as AgentIntrospectPrimitive,
    LearnPrimitive as AgentLearnPrimitive,
    LifespanPrimitive as AgentLifespanPrimitive,
    MemoryPrimitive as AgentMemoryPrimitive,
    ModelPrimitive as AgentModelPrimitive,
    ObservePrimitive as AgentObservePrimitive,
    ProbePrimitive as AgentProbePrimitive,
    RefusePrimitive as AgentRefusePrimitive,
    RepairPrimitive as AgentRepairPrimitive,
    RolePrimitive as AgentRolePrimitive,
    SoulPrimitive as AgentSoulPrimitive,
    StatePrimitive as AgentStatePrimitive,
    TrustPrimitive as AgentTrustPrimitive,
    # Compositions
    AgentComposition,
    all_compositions,
    all_primitives as all_agent_primitives,
    boot,
    collaborate,
    crisis,
    imprint,
    is_agent_primitive,
    register_all as register_all_agent_primitives,
    retire,
    supervise,
    task,
    whistleblow,
    # Event types
    all_agent_event_types,
    AGENT_IDENTITY_CREATED,
    AGENT_IDENTITY_ROTATED,
    AGENT_SOUL_IMPRINTED,
    AGENT_MODEL_BOUND,
    AGENT_MODEL_CHANGED,
    AGENT_MEMORY_UPDATED,
    AGENT_STATE_CHANGED,
    AGENT_AUTHORITY_GRANTED,
    AGENT_AUTHORITY_REVOKED,
    AGENT_TRUST_ASSESSED,
    AGENT_BUDGET_ALLOCATED,
    AGENT_BUDGET_EXHAUSTED,
    AGENT_ROLE_ASSIGNED,
    AGENT_LIFESPAN_STARTED,
    AGENT_LIFESPAN_EXTENDED,
    AGENT_LIFESPAN_ENDED,
    AGENT_GOAL_SET,
    AGENT_GOAL_COMPLETED,
    AGENT_GOAL_ABANDONED,
    AGENT_OBSERVED,
    AGENT_PROBED,
    AGENT_EVALUATED,
    AGENT_DECIDED,
    AGENT_ACTED,
    AGENT_DELEGATED,
    AGENT_ESCALATED,
    AGENT_REFUSED,
    AGENT_LEARNED,
    AGENT_INTROSPECTED,
    AGENT_COMMUNICATED,
    AGENT_REPAIRED,
    AGENT_EXPECTATION_SET,
    AGENT_EXPECTATION_MET,
    AGENT_EXPECTATION_EXPIRED,
    AGENT_CONSENT_REQUESTED,
    AGENT_CONSENT_GRANTED,
    AGENT_CONSENT_DENIED,
    AGENT_CHANNEL_OPENED,
    AGENT_CHANNEL_CLOSED,
    AGENT_COMPOSITION_FORMED,
    AGENT_COMPOSITION_DISSOLVED,
    AGENT_COMPOSITION_JOINED,
    AGENT_COMPOSITION_LEFT,
    AGENT_ATTENUATED,
    AGENT_ATTENUATION_LIFTED,
)
from .types import (
    Activation,
    ActorID,
    Cadence,
    ConversationID,
    Cursor,
    DomainScope,
    EdgeID,
    EnvelopeID,
    EventID,
    EventType,
    Hash,
    Layer,
    NonEmpty,
    Option,
    Page,
    PublicKey,
    Score,
    Signature,
    SubscriptionPattern,
    SystemURI,
    TreatyID,
    Weight,
)

__version__ = "0.3.0"
